# Generated by Django 3.1.7 on 2021-03-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.JSONField()),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
