# Generated by Django 3.1.7 on 2021-03-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curlingapp', '0002_auto_20210311_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='end',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='match',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='throw',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
