# Generated by Django 3.1.7 on 2021-03-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curlingapp', '0003_auto_20210316_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scoreboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(max_length=1)),
                ('end', models.IntegerField()),
                ('points', models.IntegerField()),
                ('match', models.CharField(max_length=120)),
            ],
        ),
    ]
