# Generated by Django 3.1.7 on 2021-03-18 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curlingapp', '0004_scoreboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(max_length=120)),
                ('camId', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='round',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curlingapp.match'),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curlingapp.match'),
        ),
    ]
