# Generated by Django 3.1.7 on 2021-03-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curlingapp', '0006_auto_20210318_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='redTeam',
            field=models.CharField(default='Red', max_length=120),
        ),
        migrations.AddField(
            model_name='match',
            name='yellowTeam',
            field=models.CharField(default='Yellow', max_length=120),
        ),
    ]
