# Generated by Django 3.1.7 on 2021-03-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curlingapp', '0007_auto_20210321_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='camId',
            field=models.IntegerField(verbose_name='Bane'),
        ),
        migrations.AlterField(
            model_name='match',
            name='matchName',
            field=models.CharField(max_length=120, verbose_name='Match'),
        ),
        migrations.AlterField(
            model_name='match',
            name='redTeam',
            field=models.CharField(default='Red', max_length=120, verbose_name='Red Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='yellowTeam',
            field=models.CharField(default='Yellow', max_length=120, verbose_name='Yellow Team'),
        ),
    ]
